apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: playground
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.34.1
    helm:
      values: |
        server:
          ui:
            enabled: true
          serviceAccount:
            create: true
            name: "vault"
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: "gp2"
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "voting-app-spot-stateful"
              effect: "PreferNoSchedule"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: workload-type
                    operator: In
                    values:
                    - voting-app-spot-stateful
          standalone:
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "file" {
                path = "/vault/data"
              }
              seal "awskms" {
                region     = "us-east-1"
                kms_key_id = "alias/voting-app-vault-unseal"
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .webhooks[].failurePolicy