apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: tg-config
  namespace: vault
spec:
  targetReference:
    group: ""
    kind: Service
    name: vault
  defaultConfiguration:
    targetType: ip
