---
- name: Configure kubeconfig using the installer role
  ansible.builtin.command:
    argv:
      - aws
      - eks
      - update-kubeconfig
      - --name
      - "{{ eks_cluster_name }}"
      - --region
      - "{{ eks_cluster_region }}"
      - --role-arn
      - "{{ installer_role_arn }}"
  changed_when: false