apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: playground
  source:
    chart: karpenter-crd
    repoURL: public.ecr.aws/karpenter
    targetRevision: 1.14.1
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true