apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-deployment.yaml
  - db-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - result-deployment.yaml
  - result-service.yaml
  - routes.yaml
  - targetgroupconfiguration.yaml
  - vote-analysistemplate.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - worker-deployment.yaml
patches:
  - path: karpenter-affinity-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "app in (result, worker)"