apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting
  labels:
    app: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: ghcr.io/gnumilanix/production-ready-voting-app-result:main-latest
          command: ["/bin/sh", "-c"]
          args: [". /vault/secrets/config && exec node server.js"]
          ports:
            - name: result
              containerPort: 80
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi