apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: vote-tg-config
  namespace: voting
spec:
  targetReference:
    group: ""
    kind: Service
    name: vote
  defaultConfiguration:
    targetType: ip
---
apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: vote-preview-tg-config
  namespace: voting
spec:
  targetReference:
    group: ""
    kind: Service
    name: vote-preview
  defaultConfiguration:
    targetType: ip
---
apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: result-tg-config
  namespace: voting
spec:
  targetReference:
    group: ""
    kind: Service
    name: result
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /result
      healthCheckProtocol: HTTP
      matcher:
        httpCode: "200,301"
    targetGroupAttributes:
      - key: stickiness.enabled
        value: "true"
      - key: stickiness.type
        value: lb_cookie
      - key: stickiness.lb_cookie.duration_seconds
        value: "86400"