global:
  domain: "" 

configs:
  cm:
    timeout.reconciliation: 600s
    timeout.reconciliation.jitter: 30s
    
controller:
  serviceAccount:
    create: true
    name: argocd-application-controller

server:
  extraArgs:
    - --insecure
  config:
    server.rootpath: /argocd
    server.basehref: /argocd/

  httproute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: voting-gateway
        namespace: voting
        sectionName: http
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /argocd
