apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-bootstrap
  namespace: argocd
spec:
  project: playground
  source:
    repoURL: https://github.com/gnumilanix/production-ready-voting-app.git
    targetRevision: main
    path: argo/rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
