apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-bootstrap
  namespace: argocd
spec:
  project: playground
  source:
    repoURL: https://github.com/gnumilanix/production-ready-voting-app.git
    targetRevision: main
    path: argo/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

