name: deploy-terraform
on:
    workflow_run:
        workflows: ["bootstrap-terraform"]
        types:
            - completed
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
    TF_VAR_aws_region: ${{ vars.AWS_REGION }}
    TF_VAR_state_bucket_name: ${{ vars.STATE_BUCKET_NAME }}

jobs:
    validate:
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              run: terraform -chdir=terraform/deploy init -backend=false

            - name: Terraform Validate
              run: terraform -chdir=terraform/deploy validate
    plan:
        runs-on: ubuntu-latest
        needs: [validate]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Configure AWS Credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: arn:aws:iam::365020425296:role/GitHubActionsTerraformRole
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              run: terraform -chdir=terraform/deploy init -backend-config=terraform/deploy/backend.hcl

            - name: Terraform Plan
              run: terraform -chdir=terraform/deploy plan -out=tfplan

            - name: Upload Plan Artifact
              uses: actions/upload-artifact@v7
              with:
                  name: tfplan-deploy
                  path: terraform/deploy/tfplan
                  retention-days: 1
    deploy:
        runs-on: ubuntu-latest
        needs: [plan]
        environment: production
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Configure AWS Credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: arn:aws:iam::365020425296:role/GitHubActionsTerraformRole
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              run: terraform -chdir=terraform/deploy init -backend-config=terraform/deploy/backend.hcl

            - name: Download Plan Artifact
              uses: actions/download-artifact@v7
              with:
                  name: tfplan-deploy
                  path: terraform/deploy/

            - name: Terraform Apply
              run: terraform -chdir=terraform/deploy apply -auto-approve tfplan
