name: deploy-terraform
on:
  workflow_run:
      workflows: ["bootstrap-terraform"]
      types:
          - completed
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
    TF_VAR_aws_region: ${{ vars.AWS_REGION }}
    TF_VAR_state_bucket_name: ${{ vars.STATE_BUCKET_NAME }}

concurrency:
  group: voting-app-terraform-deploy
  cancel-in-progress: false
  
defaults:
  run:
    working-directory: terraform/deploy

jobs:
    validate:
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              run: terraform init -backend=false

            - name: Terraform Validate
              run: terraform validate
    plan:
        runs-on: ubuntu-latest
        needs: [validate]
        env:
            TF_VAR_jump_server_ssh_cidr: ${{ vars.JUMP_SERVER_SSH_CIDR }}
            TF_VAR_jump_server_public_key: ${{ secrets.JUMP_SERVER_PUBLIC_KEY }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Configure AWS Credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: arn:aws:iam::365020425296:role/GitHubActionsTerraformRole
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              uses: ./.github/actions/terraform-init
              with:
                  working-directory: terraform/deploy
                  bucket: ${{ vars.STATE_BUCKET_NAME }}
                  key: deploy/terraform.tfstate
                  region: ${{ vars.AWS_REGION }}

            - name: Terraform Plan
              run: terraform plan -out=tfplan

            - name: Upload Plan Artifact
              uses: actions/upload-artifact@v7
              with:
                  name: tfplan-deploy
                  path: terraform/deploy/tfplan
                  retention-days: 1
    deploy:
        runs-on: ubuntu-latest
        needs: [plan]
        environment: production
        env:
            TF_VAR_jump_server_ssh_cidr: ${{ vars.JUMP_SERVER_SSH_CIDR }}
            TF_VAR_jump_server_public_key: ${{ secrets.JUMP_SERVER_PUBLIC_KEY }}
        outputs:
            jump_server_ip: ${{ steps.export-tf-outputs.outputs.JUMP_SERVER_IP }}
            eks_cluster_name: ${{ steps.export-tf-outputs.outputs.EKS_CLUSTER_NAME }}
            eks_cluster_region: ${{ steps.export-tf-outputs.outputs.EKS_CLUSTER_REGION }}
            aws_load_balancer_controller_role_arn: ${{ steps.export-tf-outputs.outputs.AWS_LOAD_BALANCER_CONTROLLER_ROLE_ARN }}
            controller_installer_role_arn: ${{ steps.export-tf-outputs.outputs.CONTROLLER_INSTALLER_ROLE_ARN }}
            vpc_id: ${{ steps.export-tf-outputs.outputs.VPC_ID }}
            vault_efs_file_system_id: ${{ steps.export-tf-outputs.outputs.VAULT_EFS_FILE_SYSTEM_ID }}
            amp_remote_write_url: ${{ steps.export-tf-outputs.outputs.AMP_REMOTE_WRITE_URL }}
            amg_workspace_id: ${{ steps.export-tf-outputs.outputs.AMG_WORKSPACE_ID }}
            amg_service_account_id: ${{ steps.export-tf-outputs.outputs.AMG_SERVICE_ACCOUNT_ID }}
            grafana_workspace_role_arn: ${{ steps.export-tf-outputs.outputs.GRAFANA_WORKSPACE_ROLE_ARN }}
            amp_workspace_id: ${{ steps.export-tf-outputs.outputs.AMP_WORKSPACE_ID }}
            amp_region: ${{ steps.export-tf-outputs.outputs.AMP_REGION }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Configure AWS Credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: arn:aws:iam::365020425296:role/GitHubActionsTerraformRole
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              uses: ./.github/actions/terraform-init
              with:
                  working-directory: terraform/deploy
                  bucket: ${{ vars.STATE_BUCKET_NAME }}
                  key: deploy/terraform.tfstate
                  region: ${{ vars.AWS_REGION }}

            - name: Download Plan Artifact
              uses: actions/download-artifact@v7
              with:
                  name: tfplan-deploy
                  path: terraform/deploy/

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan

            - name: Capture Terraform Outputs
              id: export-tf-outputs
              run: |
                echo "JUMP_SERVER_IP=$(terraform output -raw jump_server_public_ip)" >> "$GITHUB_OUTPUT"
                echo "EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)" >> "$GITHUB_OUTPUT"
                echo "EKS_CLUSTER_REGION=$(terraform output -raw eks_cluster_region)" >> "$GITHUB_OUTPUT"
                echo "AWS_LOAD_BALANCER_CONTROLLER_ROLE_ARN=$(terraform output -raw aws_load_balancer_controller_role_arn)" >> "$GITHUB_OUTPUT"
                echo "CONTROLLER_INSTALLER_ROLE_ARN=$(terraform output -raw controller_installer_role_arn)" >> "$GITHUB_OUTPUT"
                echo "VPC_ID=$(terraform output -raw vpc_id)" >> "$GITHUB_OUTPUT"
                echo "VAULT_EFS_FILE_SYSTEM_ID=$(terraform output -raw vault_efs_file_system_id)" >> "$GITHUB_OUTPUT"
                echo "AMP_REMOTE_WRITE_URL=$(terraform output -raw amp_remote_write_url)" >> "$GITHUB_OUTPUT"
                echo "AMG_WORKSPACE_ID=$(terraform output -raw amg_workspace_id)" >> "$GITHUB_OUTPUT"
                echo "AMG_SERVICE_ACCOUNT_ID=$(terraform output -raw amg_service_account_id)" >> "$GITHUB_OUTPUT"
                echo "GRAFANA_WORKSPACE_ROLE_ARN=$(terraform output -raw grafana_workspace_role_arn)" >> "$GITHUB_OUTPUT"
                echo "AMP_WORKSPACE_ID=$(terraform output -raw amp_workspace_id)" >> "$GITHUB_OUTPUT"
                echo "AMP_REGION=$(terraform output -raw amp_region)" >> "$GITHUB_OUTPUT"

    configure:
        runs-on: ubuntu-latest
        needs: [deploy]
        environment: production
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Configure AWS Credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: arn:aws:iam::365020425296:role/GitHubActionsTerraformRole
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Configure cluster with Ansible
              uses: dawidd6/action-ansible-playbook@v9
              env:
                  ARGOCD_REPO_TOKEN: ${{ secrets.ARGOCD_REPO_TOKEN }}
              with:
                  playbook: configure-cluster.yml
                  directory: ansible
                  key: ${{ secrets.JUMP_SERVER_PRIVATE_KEY }}
                  inventory: |
                      [jump_server]
                      ${{ needs.deploy.outputs.jump_server_ip }} ansible_user=ec2-user

                      [jump_server:vars]
                      eks_cluster_name=${{ needs.deploy.outputs.eks_cluster_name }}
                      eks_cluster_region=${{ needs.deploy.outputs.eks_cluster_region }}
                      vpc_id=${{ needs.deploy.outputs.vpc_id }}
                      vault_efs_file_system_id=${{ needs.deploy.outputs.vault_efs_file_system_id }}
                      controller_role_arn=${{ needs.deploy.outputs.aws_load_balancer_controller_role_arn }}
                      installer_role_arn=${{ needs.deploy.outputs.controller_installer_role_arn }}
                      amp_remote_write_url=${{ needs.deploy.outputs.amp_remote_write_url }}
                      amg_workspace_id=${{ needs.deploy.outputs.amg_workspace_id }}
            - name: Configure Grafana AMP data source
              uses: dawidd6/action-ansible-playbook@v9
              with:
                  playbook: install-grafana.yml
                  directory: ansible
                  inventory: |
                      [local]
                      localhost ansible_connection=local amg_workspace_id=${{ needs.deploy.outputs.amg_workspace_id }} amg_service_account_id=${{ needs.deploy.outputs.amg_service_account_id }} grafana_role_arn=${{ needs.deploy.outputs.grafana_workspace_role_arn }} amp_workspace_id=${{ needs.deploy.outputs.amp_workspace_id }} amp_region=${{ needs.deploy.outputs.amp_region }}
